### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected "Lets" to "Let's".
Corrected "its" to "it's".

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by leopardracer** [comment]
@jeremyfelder Hi! Apologies for the inconvenience. I just wanted to check if there’s anything I can improve in my pull request. Please feel free to ask any questions or let me know if any changes are needed to meet the project's merge requirements. I’m happy to make adjustments!

**Comment by jeremyfelder** [comment]
Hi @leopardracer. We occasionally go through our docs to fix all the spelling mistakes and therefore don't usually approve typo only PRs unless they clarify some context in doing so.

Are you using ICICLE for a project?

**Comment by leopardracer** [comment]
@jeremyfelder Hi! Thanks for the feedback. I understand that you prioritize changes beyond just typos, but I believe even small improvements to the documentation, like correcting typos, contribute to a better experience for users and developers.
Yes, I am using ICICLE for a project, and I thought fixing these minor mistakes would help future users. Let me know if you'd like me to adjust the PR to include further context or other changes.

**Comment by jeremyfelder** [comment]
> Yes, I am using ICICLE for a project

Awesome, glad to hear! If you have any requests for features or questions, let us know and we'd be happy to help!

> Let me know if you'd like me to adjust the PR to include further context or other changes.

We do appreciate the find, though as is we can't merge this PR as it will invite other typos only PRs that don't enhance the clarity of the documentation. 
If you find other areas where the documentation isn't clear, we'd be happy to merge a PR that includes changes to enhance the clarity of the documentation

**Pull request closed without merging**
